spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_stock_db?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
    port: 8884   
    
flickr:
    apiKey: c582f7f4cb0da8cddd64aa1fff75145b
    apiSecret: 657529e4da2fa9ae
    appKey: 72157719057798209-c828e4c0fae03508
    appSecret: 17297a6b84cadf67
   
    